spring.datasource.url=jdbc:mysql://localhost:3306/task_manager?serverTimeZone=UTC
spring.datasource.username=root
spring.datasource.password=root123!@#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.neo4j.url=neo4j://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=roo123!@#


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:/db.changelog/db.changelog-master.yaml

spring.jackson.deserialization.fail-on-unknown-properties=true

jwt.expiration=9000000
jwt.secretString=141592653589793238462643383279502884197169399375105820974944592307816406286\
  2089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027\
  01938521105559644622948954930381964428

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mate.tasks.manager@gmail.com
spring.mail.password=jnplhfzamuamxntu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

google.client-id=30635903239-2k9pvcdhvk89aapab6mluhflj7hqpgr3.apps.googleusercontent.com
google.token-url=https://accounts.google.com

dropbox.application.name=mate.tasks.manager
dropbox.client_id=vhnlvxh2hjxkwr9
dropbox.client_secret=196tp2iodog2mgm
dropbox.token_url=https://api.dropbox.com/oauth2/token
dropbox.token=KcYnIg7jjoMAAAAAAAAAATz\
  -rCR0t1pRjjO-6TKKw8Le7po7YxIWQhRktqH4VElv

jasypt.encryptor.password=ENC(askygdq8PHapYFnlX6WsTwZZOxWInq+i)
